---
- name: Install and start Nginx
  hosts: your_target_host
  become: yes  # Use 'sudo' to run commands as root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
